services:
  web:
    build: .
    container_name: compare50_web
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      APPLICATION_ENV: dev
      MYSQL_DATABASE: compare50
      MYSQL_HOST: mysql
      MYSQL_PASSWORD: crimson
      MYSQL_USERNAME: root
      OAUTHLIB_INSECURE_TRANSPORT: 1
    links:
      - mysql
    ports:
      - "8080:8080"
    volumes:
      - .:/var/www
  mysql:
    image: cs50/mysql
    environment:
      MYSQL_DATABASE: compare50
      MYSQL_ROOT_PASSWORD: crimson
    healthcheck: # https://github.com/docker/compose/issues/374#issuecomment-284695410
      interval: 1s
      retries: 30
      test: mysqladmin -uroot -pcrimson ping
version: "2.1"
